name: bump
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  update:
    runs-on: depot-ubuntu-24.04-4
    container:
      image: ghcr.io/bearcove/beardist:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_READWRITE_TOKEN }}
      CLICOLOR: 1
      CLICOLOR_FORCE: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          beardist update-tap
